name: Deploy to Hostinger

on:
  push:
    branches: [ "main" ]

jobs:
  build-admin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Admin
        run: |
          cd Admin
          npm install
          npm run build

      - name: Upload Admin via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_SERVER_ADMIN }}   # ftp.peru-mandrill-728053.hostingersite.com
          username: ${{ secrets.FTP_USERNAME_ADMIN }}
          password: ${{ secrets.FTP_PASSWORD_ADMIN }}
          protocol: ftps
          port: 21
          local-dir: ./Admin/dist/
          server-dir: /public_html/admin/

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Frontend
        run: |
          cd Frontend
          npm install
          npm run build

      - name: Upload Frontend via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_SERVER_FRONTEND }}   # ftp.peru-mandrill-728053.hostingersite.com
          username: ${{ secrets.FTP_USERNAME_FRONTEND }}
          password: ${{ secrets.FTP_PASSWORD_FRONTEND }}
          protocol: ftps
          port: 21
          local-dir: ./Frontend/dist/
          server-dir: /public_html/
