name: Deploy to Hostinger

on:
  push:
    branches: [ "main" ]

jobs:
  build-admin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Admin
        run: |
          cd Admin
          npm install
          npm run build

      - name: Upload Admin via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_SERVER_ADMIN }}  
          username: ${{ secrets.FTP_USERNAME_ADMIN }}
          password: ${{ secrets.FTP_PASSWORD_ADMIN }}
          protocol: ftp
          port: 21
          local-dir: ./Admin/dist/
          server-dir: /public_html/
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Upload Frontend via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_SERVER_FRONTEND }}  
          username: ${{ secrets.FTP_USERNAME_FRONTEND }}
          password: ${{ secrets.FTP_PASSWORD_FRONTEND }}
          protocol: ftp
          port: 21
          local-dir: ./frontend/dist/
          server-dir: /public_html/
